### ISSUE TITLE
[feat] 로그인 기능 구현

### ISSUE THREAD

**Issue by Eric030406** [Toughie17/MACC_TEAM4_HODORI#2]
## 📍이슈
Firebase Auth를 이용한 로그인 및 관련 기능들을 구현합니다

##  🐯 todo
- [x] AuthManager 구현
- [x] 팀 모델 구현
- [x] 네비게이션 모델 구현
- [x] 회원가입 구현
- [x] 비밀번호 찾기 구현
- [x] 이메일 인증 구현
