### ISSUE TITLE
[feat] TimerView 구현

### ISSUE THREAD

**Issue by mango306** [Toughie17/MACC_TEAM4_HODORI#24]
## 📍이슈
-- 타이머 버튼을 눌렀을 때 뜨는 타이머 뷰를 구현

##  🐯 todo
- [] TimerView 구현
- [] Timer 나타나는 로직 구현
- [] Timer 일시정지 구현
- [] Timer 정지 구현
