### ISSUE TITLE
[feat] 애니메이션(Lottie) 구현 && 뷰 디자인 시스템 적용

### ISSUE THREAD

**Issue by Toughie17** [Toughie17/MACC_TEAM4_HODORI#29]
## 📍이슈
-- 미팅뷰에 들어갈 Lottie 애니메이션을 추가하고, 여러 뷰들의 컬러 및 폰트, 패딩을 조정합니다.

##  🐯 todo
- [ ] LottieView 구현
- [ ] 컬러 익스텐션 추가
- [ ] 폰트 익스텐션 추가
- [ ] 뷰별 디자인 시스템 체크 및 적용__
