### ISSUE TITLE
[feat] StartView 구현

### ISSUE THREAD

**Issue by 00306** [Toughie17/MACC_TEAM4_HODORI#30]
## 📍이슈
앱의 첫 진입점인 StartView를 구현합니다.

##  🐯 todo
- [x] 직전 회의 기록 카드 구현
- [x] AgendaSettingView로 네비게이션되는 버튼 구현
- [x] HistoryView로 네비게이션되는 버튼 구현
- [x] RealmManager 구현
- [x]  CoreDataManager 구현
